### ISSUE TITLE
Does this run on a Mac? Can I call it from within my Rust program?

### ISSUE THREAD

**Issue by wbpaley** [pwnwriter/haylxon#109]
### Description

Thanks for this! 
Look forward to getting it working.

I compiled in RustRover & it runs fine, but can't instantiate Brave or Chrome.

Here's a grab from _terminal_; line 1 gets the error on line 2, line 3 opens Brave successfully so I know the path is correct.

```
brad@Hutchins debug % ./hxn -b "/Applications/Brave Browser.app" --url https://didi.co
error: Error instantiating browser /Applications/Brave Browser.app
brad@Hutchins debug % /usr/bin/open -a "/Applications/Brave Browser.app" https://didi.co
brad@Hutchins debug %
``` 

Am I doing something wrong--or maybe it doesn't run on Macs?

**And the end goal: how do I call it from within a Rust program?**
(I assume I could just cut & paste the contents of main() in main.rs--but is there an API?)

Thanks!
Brad

**Comment by pwnwriter** [comment]
You should pass the binary path like this below.

<img width="1272" alt="Screenshot 2024-07-04 at 10 00 10" src="https://github.com/pwnwriter/haylxon/assets/90331517/05b30118-f7b8-40fd-be5f-6ce9a0e12191">


<img width="1253" alt="Screenshot 2024-07-04 at 10 00 20" src="https://github.com/pwnwriter/haylxon/assets/90331517/c6f9804f-ed42-4dd4-991b-1db5821f9aa7">






***And the end goal: how do I call it from within a Rust program?***

I'm afraid, this is not possible since `haylxon` is not a `(library)` rather an application binary.

**Comment by wbpaley** [comment]
Thank you!
